### ISSUE TITLE
DRY on EH Dispatcher

### ISSUE THREAD

**Issue by DCPDamon** [Solution-Management/CtrlVAF#5]
Hey team, I've never collaborated on github before, so I don't know how to suggest code changes.  So I'm opening an issue and just pasting my code here.  I think I found a way to fully DRY Event Handling Dispatching.  Note that the code below doesn't include licensing or caching or some of the fancy stuff you have, but I think you can apply all of that on top of the code below.

Here's the dispatcher class. I assumed we can't add assemblies in runtime, so I just loaded all the types in all the assemblies when instantiated and reference that list. When I call the dispatch method I pass in the command as you do, but I also pass in the MFEventHandlerType that triggered the event.  I find all the classes that have the right interface (same as you).  I also filter down to classes that have an attribute of class EventHandlerDispatcherAttribute.

```
public class Dispatcher
{
    private readonly List<Type> AssemblyTypes = Assembly.GetExecutingAssembly().GetTypes().ToList();

    public void DispatchEventHandler<TCommand>(MFEventHandlerType mFEventHandlerType, TCommand command) where TCommand : class
    {
        Type handlerType = typeof(ICommandHandler<>).MakeGenericType(command.GetType());

        AssemblyTypes
            .Where(t =>
                   t.IsClass
                && t.GetInterfaces().Contains(handlerType)
                && t.GetCustomAttributes<EventHandlerDispatcherAttribute>().Any(a => a.EventHandlerTypeMatches(mFEventHandlerType)))
            .ToList()
            .ForEach(type => (Activator.CreateInstance(type) as ICommandHandler<TCommand>).Handle(command));
    }
}
```

Here's the EventHandlerDispatcherAttribute class.  It is essentially the same as EventHandlerAttribute, I just didn't know if I could use it without creating issues.  So I made a new one where you just set the MFEventHandlerType.

```
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
public class EventHandlerDispatcherAttribute : Attribute
{
    private readonly MFEventHandlerType EventHandlerType;

    public EventHandlerDispatcherAttribute(MFEventHandlerType eventHandlerType) => EventHandlerType = eventHandlerType;

    public bool EventHandlerTypeMatches(MFEventHandlerType eventHandlerType) => EventHandlerType == eventHandlerType;
}
```

So then the handling class (like the one below) just has to make sure it references the interface (to ensure it has a Handle method) and the EventHandlerDispatcherAttribute (to specify which event handler types it should process - could be multiple).

```
[EventHandlerDispatcher(MFEventHandlerType.MFEventHandlerBeforeLogoutFromVault)]
public class EHBeforeLogoutFromVaultHandler : ICommandHandler<EventHandlerCommand<Configuration>>
{
    public void Handle(EventHandlerCommand<Configuration> command)
    {
        // Do stuff
    }
}
```

For reference, here is the Interface:

```
public interface ICommandHandler<TCommand> where TCommand : class
{
    void Handle(TCommand command);
}
```

And here is the Command class:

```
public class EventHandlerCommand<TConfiguration>
{
    public EventHandlerEnvironment Env { get; set; }
    public TConfiguration Configuration { get; set; }
}
```

With all of that in play, here is what VaultApplication.cs looks like:

```
public class VaultApplication
        : ConfigurableVaultApplicationBase<Configuration>
    {
        readonly Dispatcher Dispatcher = new Dispatcher();

        [EventHandler(MFEventHandlerType.MFEventHandlerAfterCreateNewObjectFinalize)]
        [EventHandler(MFEventHandlerType.MFEventHandlerAfterCheckInChangesFinalize)]
        [EventHandler(MFEventHandlerType.MFEventHandlerAfterLoginToVault)]
        [EventHandler(MFEventHandlerType.MFEventHandlerBeforeCheckInChanges)]
        [EventHandler(MFEventHandlerType.MFEventHandlerBeforeLogoutFromVault)]
        public void EHCommandGenerator(EventHandlerEnvironment env)
            => Dispatcher.DispatchEventHandler(env.EventType, new EventHandlerCommand<Configuration> { Env = env, Configuration = Configuration });
    }
```

I hope all of this makes sense.  It's working for me with limited testing.  Let me know what you think!

**Comment by SoftAdviceJR** [comment]
I did not know you had access to the event type from within env. Your idea does make a lot of sense then.

@FredTheDane also suggested using attributes to bind handlers instead of the inheritance. We could do that. It would make it so you only really need one command type per dispatcher type. Thinking about it again, that does seem more user friendly than making multiple different commands for each event type.

I'll have to look into how to pass the event type into the Dispatch() method though.

**Comment by FredTheDane** [comment]
Great suggestion.

I remember back when I first set up the CommandDispatcher, with a command class for each and every type of eventhandler. It felt excessive and wrong to me back then, but did not really know how to get about attributes and all that.

I will let you work on this if you have the time to spare @SoftAdviceJR :) Do let me know if you have any issues implementing it.
